# Generated by Django 4.1.3 on 2022-12-05 04:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            # field='joe',
            preserve_default=False,
        ),
    ]
