# Generated by Django 4.1.3 on 2022-12-05 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_watchlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watchlists',
            new_name='Watchlist',
        ),
    ]
